version: '{build}'
skip_tags: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Y9F06cMPu5fLcnOja8pRUVuZb20tTZ0+qU9fAN1EyYaSOnbxTbDdyswaxWjWKHoK
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: IDk/97Ly58MKKAMggkyTCZnU0w2e8c0g14+G9l9aEws4x/ObcdY4yQ3eXqluTV/3
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
